// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {highlight} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#YOQOPOOQYOPOOOTOPOOObOQO'#CdOjOPO'#C`OuOSO'#CcQOOOOOQ]OPOOOOOO'#Ce'#CeOzOQO,59OOOOO-E6b-E6bO!]OPO,58}OOOO-E6c-E6cO!eOSO'#CfO!jOPO1G.iOOOO,59Q,59QOOOO-E6d-E6d",
  stateData: "!x~OQQORPO~O[RO]TO~OTWOUWO~O[ROZSX]SX~O^ZO~OTWOUWOZWa[Wa]Wa~O_]OZVa~O^_O~O_]OZVi~OQRTUT~",
  goto: "uZPPPP[PP_cioRVPTUPVQSPRYSQXRR[XQ^ZR`^",
  nodeNames: "⚠ url Protocol Host Path Placeholder PathSegment Query",
  maxTerm: 15,
  propSources: [highlight],
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: ",k~RhOs!mtv!mvw#_w}!m}!O#{!O!P#{!P!Q%_!Q![%d![!]#{!]!a!m!a!b'x!b!c!m!c!}'}!}#O#{#O#P!m#P#Q#{#Q#R!m#R#S#{#S#T!m#T#o'}#o#p+Z#p;'S!m;'S;=`#X<%lO!mQ!rVUQOs!mt!P!m!Q!a!m!b#o!m#p;'S!m;'S;=`#X<%lO!mQ#[P;=`<%l!mR#fV_PUQOs!mt!P!m!Q!a!m!b#o!m#p;'S!m;'S;=`#X<%lO!mR$ScRPUQOs!mt}!m}!O#{!O!P#{!Q![#{![!]#{!]!a!m!b!c!m!c!}#{!}#O#{#O#P!m#P#Q#{#Q#R!m#R#S#{#S#T!m#T#o#{#p;'S!m;'S;=`#X<%lO!m~%dO[~V%me^SRPUQOs!mt}!m}!O#{!O!P#{!Q![%d![!]#{!]!_!m!_!`'O!`!a!m!b!c!m!c!}%d!}#O#{#O#P!m#P#Q#{#Q#R!m#R#S#{#S#T!m#T#o%d#p;'S!m;'S;=`#X<%lO!mU'VZ^SUQOs!mt!P!m!Q!['O![!a!m!b!c!m!c!}'O!}#T!m#T#o'O#p;'S!m;'S;=`#X<%lO!m~'}O]~V(We^SRPUQOs!mt}!m}!O#{!O!P#{!Q![%d![!])i!]!_!m!_!`'O!`!a!m!b!c!m!c!}'}!}#O#{#O#P!m#P#Q#{#Q#R!m#R#S#{#S#T!m#T#o'}#p;'S!m;'S;=`#X<%lO!mR)pdRPUQOs!mt}!m}!O#{!O!P#{!P!Q+O!Q![#{![!]#{!]!a!m!b!c!m!c!}#{!}#O#{#O#P!m#P#Q#{#Q#R!m#R#S#{#S#T!m#T#o#{#p;'S!m;'S;=`#X<%lO!mP+RP!P!Q+UP+ZOQP~+^VOs+st!P+s!Q!a+s!b#q+s#r;'S+s;'S;=`,e<%lO+s~+vWOs+st!P+s!Q!a+s!b#q+s#q#r,`#r;'S+s;'S;=`,e<%lO+s~,eOT~~,hP;=`<%l+s",
  tokenizers: [0, 1, 2],
  topRules: {"url":[0,1]},
  tokenPrec: 80
})
